"""test

Revision ID: 0e6714a8e574
Revises: 
Create Date: 2023-05-16 17:59:29.501721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6714a8e574'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('red', sa.Boolean(), nullable=True),
    sa.Column('blue', sa.Boolean(), nullable=True),
    sa.Column('green', sa.Boolean(), nullable=True),
    sa.Column('purple', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancel', sa.Boolean(), nullable=True),
    sa.Column('collect', sa.Boolean(), nullable=True),
    sa.Column('destroy', sa.Boolean(), nullable=True),
    sa.Column('discarded', sa.Boolean(), nullable=True),
    sa.Column('draw', sa.Boolean(), nullable=True),
    sa.Column('expansion', sa.Boolean(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.Column('renews', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_maps')
    op.drop_table('color_maps')
    op.drop_table('cards')
    # ### end Alembic commands ###
