"""test

Revision ID: 8175e8305e37
Revises: 
Create Date: 2023-06-06 15:31:53.928838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8175e8305e37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('master_account', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('collected_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_collected_cards_card_id_cards')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collected_cards_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('red', sa.Boolean(), nullable=True),
    sa.Column('blue', sa.Boolean(), nullable=True),
    sa.Column('green', sa.Boolean(), nullable=True),
    sa.Column('purple', sa.Boolean(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_color_maps_card_id_cards')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancel', sa.Boolean(), nullable=True),
    sa.Column('collect', sa.Boolean(), nullable=True),
    sa.Column('destroy', sa.Boolean(), nullable=True),
    sa.Column('discarded', sa.Boolean(), nullable=True),
    sa.Column('draw', sa.Boolean(), nullable=True),
    sa.Column('expansion', sa.Boolean(), nullable=True),
    sa.Column('remove', sa.Boolean(), nullable=True),
    sa.Column('renews', sa.Boolean(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_keyword_maps_card_id_cards')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_maps')
    op.drop_table('color_maps')
    op.drop_table('collected_cards')
    op.drop_table('users')
    op.drop_table('decks')
    op.drop_table('cards')
    # ### end Alembic commands ###
